# This is a basic workflow to help you get started with Actions

name: CI

env:
  # commit shasum for the reproschema we want to get
  CHECKSUM: a45efccdb7d3d7f90a6b54e6f0ba2a4137e40661

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Checks that our JSON are valid
    - name: Check for syntax errors
      run: |
        npm install -g jsonlint
        grep -r  "@context" activities | cut -d: -f1 | xargs -I fname jsonlint -q fname
        grep -r  "@context" protocols | cut -d: -f1 | xargs -I fname jsonlint -q fname

    # Checks that the schemas are valid
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install reproschema requests_cache
        
    - name: Test with pyshacl
      run: |
        reproschema -l DEBUG validate activities
        reproschema -l DEBUG validate protocols/neurovault/neurovault_schema

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        curl -O -sSL https://github.com/ReproNim/reproschema-ui/archive/${CHECKSUM}.zip
        unzip ${CHECKSUM}.zip
        mv reproschema* ui
        cd ui
        cp -r ../ui-changes/. .
        npm install
        npm run build
        touch dist/.nojekyll

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      if: github.ref == 'refs/heads/master'
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: ui/dist # The folder the action should deploy.
